name: Main Workflow
on: pull_request
jobs:
  test-elixir:
    runs-on: ubuntu-latest
    container: elixir:${{ matrix.elixir_version }}-slim

    strategy:
      matrix:
        elixir_version: ["1.8", "1.9", "1.10", "1.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install --no-install-recommends -y git build-essential
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - run: mix test
      - run: EXQLITE_INTEGRATION=true mix test
